apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-games
  annotations:
    github.com/project-slug: ac-chiragmalik/github-games
spec:
  type: other
  lifecycle: development
  owner: chiragGroup

---  

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  lifecycle: production
  type: website
  owner: john@example.com

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test-comp
  description: A test 
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  lifecycle: production
  type: org web
  owner: john@example.com

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: chiragmalik31
spec:
  memberOf: [cmguests]
  lifecycle: production
  profile:
    email: chiragmalik31@demo.com
    displayName: chiragmalik31
    name: chiragmalik31   

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: malik
spec:
  memberOf: [cmguests]
  lifecycle: development
  profile:
    email: malik@xyz.com
    displayName: malik
    name: malik    
